version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    env_file:
      - .env.docker
    environment:
      - REACT_APP_POCKETBASE_URL=http://pocketbase:${PB_PORT}
      - REACT_APP_RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
    depends_on:
      - pocketbase

  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/pb/pb_data
      - pb_config:/pb/pb-config
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8090/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  pocketbase_data:
  pb_config:
